services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: fastapi
      MYSQL_DATABASE: fastapi
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
